### ISSUE TITLE
json.dump with indent should not add trailing spaces.

### ISSUE THREAD

**Issue by Parakleta** [drbild/json2yaml#1]
If using the `indent` option to `json.dump` the `separators` argument should be set to `(',',': ')` (i.e. set the item separator to not contain a space).  Without this change the conversion leaves lines with trailing whitespace which causes some editors and VCS to complain.

The `json.dump` function also doesn't terminate the last line with a newline character which should be added.

As a feature request I would like the indent to default to 2 instead of 4 to make it match the indentation of the yaml files, or else have it as a command line option.

**Comment by drbild** [comment]
Thanks for the bug report and suggestion.  I just pushed version 1.1.0, which has these fixes.

I left the default spacing at 4 for now (my preference for JSON), so use the (-i | --indent) flag to change it.

**Comment by Parakleta** [comment]
Thanks.  This still doesn't terminate the last line with a newline character.

**Comment by drbild** [comment]
Oops, missed that one!  Try version 1.1.1.

**Comment by Parakleta** [comment]
All good.  Thanks.
